var emp=[{
    "IDemp":1,
    "Name":"นางสาวโว่งว๊อก ค๊อกแค๊ก",
    "Dept":"IT",
    "Position":"IT Service",
    "salaryRate":42000,
    "Bonus":"S",
},{
    "IDemp":2,
    "Name":"นายจุ๊กกรู๊ว จุ๊กจุ๊ก",
    "Dept":"IT",
    "Position":"System Enginer",
    "salaryRate":33000,
    "Bonus":"A",
},{
    "IDemp":3,
    "Name":"นางสีแหบ แสบทรวง",
    "Dept":"HR",
    "Position":"HR",
    "salaryRate":99000,
    "Bonus":"C",
},{
    "IDemp":4,
    "Name":"นางสาวสีเหย เสยสูง",
    "Dept":"IT",
    "Position":"IT Service",
    "salaryRate":29000,
    "Bonus":"B",
},{
    "IDemp":5,
    "Name":"นายยุบยิบ ขมิบวาน",
    "Dept":"HR",
    "Position":"HR",
    "salaryRate":25000,
    "Bonus":"A",
},{
    "IDemp":6,
    "Name":"นายลำแรง แซงยุบยิบ",
    "Dept":"Account",
    "Position":"Account",
    "salaryRate":22220,
    "Bonus":"S",
},{
    "IDemp":7,
    "Name":"นายค่อยทำ รำคาน",
    "Dept":"Account",
    "Position":"Account",  
    "salaryRate":20000,
    "Bonus":"A",
},{
    "IDemp":8,
    "Name":"นางจุ้มเหลียด เสียดสี",
    "Dept":"Account",
    "Position":"Account",
    "salaryRate":20000,
    "Bonus":"C",
},{
    "IDemp":9,
    "Name":"นางสาวร้อยคู่ หดหู่หัวใจ ",
    "Dept":"IT",
    "Position":"System Account",
    "salaryRate":20000,
    "Bonus":"A",
}]
